### ISSUE TITLE
Can't display album artwork.

### ISSUE THREAD

**Issue by jennergray** [espeon/LyrThing#1]
Current Vesion : v0.1.1-patch-1
Deskthing Version: V0.10.2
Hi, I really love your app, and it works great, but the album artwork doesn't show. However, when I adjust the volume, the album artwork temporarily appears for a second and then quickly fades out.

**Comment by espeon** [comment]
think i've fixed this with the next lyrthing update. from what i can tell the issue has to do with a regression(?) of the last deskthing update and my code which didn't handle that correctly.

**Comment by espeon** [comment]
https://github.com/espeon/LyrThing/releases/tag/v0.1.2 should close this. Thanks for bringing this to my attention!
